apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh-marketplace.kubernetes
  annotations:
    codefresh-marketplace/description: 'Execute operations against a Kubernetes cluster'
    codefresh-marketplace/categories: 'deployment'
    codefresh-marketplace/icon/url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@new_struct/coming-soon/kubernetes/icon.svg"
    codefresh-marketplace/icon/background: "#f4f4f4"
spec:
  templates: []
